version: '3'

services:
  db:
    image: postgres
    ports: ["6543:5432"]
    environment:
    - POSTGRES_DB=concourse
    - POSTGRES_USER=dev
    - POSTGRES_PASSWORD=

  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports: ["8080:8080"]
    environment:
    - CONCOURSE_POSTGRES_HOST=db
    - CONCOURSE_POSTGRES_USER=dev
    - CONCOURSE_POSTGRES_PASSWORD=dev
    - CONCOURSE_POSTGRES_DATABASE=concourse
    - CONCOURSE_EXTERNAL_URL=http://localhost:8080
    - CONCOURSE_ADD_LOCAL_USER=test:test,guest:guest
    - CONCOURSE_MAIN_TEAM_LOCAL_USER=test
    - CONCOURSE_LOG_LEVEL=debug
    - CONCOURSE_DUMMY_CREDS_VAR=pipeline_var=SOME_VAR,platform=linux,ubuntu_tag=xenial,run_path=bash

  worker:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
    image: concourse/concourse:local
    command: worker
    cap_add: [SYS_ADMIN]
    stop_signal: SIGUSR2
    ports: ["7777:7777", "7788:7788"]
    environment:
    - CONCOURSE_LOG_LEVEL=debug
    - CONCOURSE_TSA_HOST=web:2222
    - CONCOURSE_EPHEMERAL=${CONCOURSE_EPHEMERAL:-true}

      # avoid using loopbacks
    # - CONCOURSE_BAGGAGECLAIM_DRIVER=overlay

      # so we can reach Garden/Baggageclaim for debugging
    - CONCOURSE_BIND_IP=0.0.0.0
    - CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0

      # so that CI can configure a different network range that doesn't overlap
      # with the outer Garden
    - CONCOURSE_GARDEN_NETWORK_POOL

      # so that these can be enabled on ChromeOS devices
    - CONCOURSE_GARDEN_USE_HOUDINI=true
    - CONCOURSE_BAGGAGECLAIM_DISABLE_USER_NAMESPACES=true
