---
resources_types:
- name: git
  type: registry-image
  source: {repository: concourse/git-resource}

resources:
- name: concourse
  type: git
  source:
    uri: https://github.com/vito/concourse
    branch: test-creds

jobs:
- name: test
  plan:
  - get: concourse
  - task: test
    file: concourse/ci/tasks/test-creds.yml
    vars:
      some_var: hi_im_some_var
      pipeline_var: overruled
      some_renamed_var: ((pipeline_var))
